### PR TITLE
Changelog on gitflow start

### PR DESCRIPTION
**Pull request by zymartinez**
Generate a CHANGELOG.md file on `gitflow release start --recommended`. Closes https://github.com/viyahe/development/issues/112

### CODE REVIEW

**Comment by hmngwy** [comment]
Ah did you mean `gitflow release start`?

**Review by hmngwy — APPROVED** [review]

**Review by hmngwy — COMMENTED** [review]
I think my only comment is that you should fix your editors whitespace hehe.

**Comment by hmngwy** [comment]
Nice, merge it.

**Comment by zymartinez** [comment]
updated the description too for documentation. CHANGELOG.md genration requires the `--recommended` flag

**Pull request merged**
